# Generated by Django 5.2.9 on 2026-01-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnet',
            new_name='Student',
        ),
    ]
