from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

# ------------------------------------------------------------
# DRF DefaultRouter setup
# ------------------------------------------------------------
# DefaultRouter automatically generates a set of URL patterns
# for a ViewSet (list, create, retrieve, update, delete, etc.)
# and also includes a default API root view.
router = DefaultRouter()

# Register the EmployeeViewset with the router.
# 'employees' is the URL prefix (e.g. /employees/, /employees/<pk>/).
# 'basename' is used to build the reverse URL names like:
#   - employee-list
#   - employee-detail
router.register('employees', views.EmployeeViewset, basename='employee')

# ------------------------------------------------------------
# URL patterns for the app
# ------------------------------------------------------------
urlpatterns = [
    # ----------------------------
    # Function-based views (Students)
    # ----------------------------
    # /students/ → list all students or create a new one (depending on implementation)
    path('students/', views.studentsView),
    # /students/<pk>/ → get, update, or delete a single student
    path('students/<int:pk>/', views.studentDetailView),
    
    # ----------------------------
    # Class-based views for Employees (alternative to router)
    # ----------------------------
    # These are commented out because you're using a ViewSet + Router
    # instead. They show how you would wire normal CBVs.
    
    # /employees/ → list employees or create a new employee
    # path('employees/', views.Employees.as_view()),  # Class-based view for Employee list/create
    
    # /employees/<pk>/ → retrieve, update, or delete a single employee
    # path('employees/<int:pk>/', views.EmployeeDetail.as_view()),

    # ----------------------------
    # Router-generated URLs
    # ----------------------------
    # Include all URLs generated by DefaultRouter.
    # This will create endpoints like:
    #   - /employees/           → EmployeeViewset.list
    #   - /employees/<pk>/      → EmployeeViewset.retrieve
    #   - plus create/update/delete routes
    path('', include(router.urls)),
]